---
- hosts: all
  remote_user: vagrant

  tasks:
  - name: dayone container
    docker_container:
      name: dayone
      image: luliang2000/dayone
      state: started
      expose:
      - 8085
      ports:
      - "8085:8085"